-- Migration manual: tabela de tokens de redefinição de senha + bootstrap do
-- primeiro usuário ADMIN.
--
-- Contexto: psicólogo hoje só ganha senha se alguém inserir `password`
-- (BCrypt) manualmente via pgweb, ou entra só por Google. Esta migration
-- prepara o backend para (1) fluxo self-service de "esqueci minha senha"
-- (POST /auth/forgot-password, /auth/reset-password) e (2) cadastro de
-- psicólogo automatizado por um admin autenticado (POST /admin/psychologists)
-- em vez de INSERT manual.
--
-- `type` em `users` é VARCHAR(15) sem CHECK constraint — o novo valor `ADMIN`
-- do enum Java não exige alteração de coluna.
--
-- Este projeto não usa Flyway/Liquibase (spring.jpa.hibernate.ddl-auto:
-- validate em todos os ambientes) — rodar manualmente, uma única vez, em cada
-- ambiente com dados reais (ex.: prod), ANTES do deploy do /api que introduz
-- as entidades/endpoints novos (lição da Fase 5a: nunca subir código que
-- espera uma tabela/coluna que ainda não existe no banco).
--
-- Idempotente: `CREATE TABLE IF NOT EXISTS` e o INSERT do admin é condicionado
-- a `NOT EXISTS` pelo e-mail — rodar de novo não duplica nem falha.

BEGIN;

CREATE TABLE IF NOT EXISTS password_reset_tokens (
	id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	id_user BIGINT NOT NULL,
	token_hash VARCHAR(255) NOT NULL,
	expires_at TIMESTAMP NOT NULL,
	consumed_at TIMESTAMP,
	created_at DATE NOT NULL,
	updated_at DATE NOT NULL,
	active BOOLEAN NOT NULL
);

-- Postgres não suporta "ADD CONSTRAINT IF NOT EXISTS" nativamente — sem este
-- DO block, rodar a migration uma segunda vez falha com "constraint already
-- exists" e desfaz a transação inteira (visto na prática ao testar em Postgres
-- isolado antes de aplicar em prod).
DO $$
BEGIN
	IF NOT EXISTS (
		SELECT 1 FROM pg_constraint WHERE conname = 'fk_password_reset_tokens_id_user'
	) THEN
		ALTER TABLE password_reset_tokens
			ADD CONSTRAINT fk_password_reset_tokens_id_user FOREIGN KEY (id_user) REFERENCES users(id);
	END IF;

	IF NOT EXISTS (
		SELECT 1 FROM pg_constraint WHERE conname = 'uq_password_reset_tokens_token_hash'
	) THEN
		ALTER TABLE password_reset_tokens
			ADD CONSTRAINT uq_password_reset_tokens_token_hash UNIQUE (token_hash);
	END IF;
END $$;

-- Bootstrap do primeiro ADMIN: nasce sem senha (password NULL) e com
-- profile_complete=true (não passa pelo fluxo de completar perfil, que é
-- específico de psicólogo). Depois de rodar esta migration, use "Esqueci
-- minha senha" na tela de login com este e-mail para definir a senha — evita
-- guardar qualquer hash/senha em texto neste arquivo.
INSERT INTO users (name, email, type, profile_complete, created_at, updated_at, active)
SELECT 'Arthur', 'remindappbr@gmail.com', 'ADMIN', TRUE, CURRENT_DATE, CURRENT_DATE, TRUE
WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = 'remindappbr@gmail.com');

COMMIT;
